config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :sessions, only: [:create, :new, :destroy]
    resources :cards, only: [:index, :destroy]
  end

  resources :sessions
  resources :user_cards
  resources :cards
  resources :users
  delete '/logout' => 'sessions#destroy'
  root 'users#index'

  get '/cookie-example' => 'cookie_example#index'

  post '/share-end' => 'user_cards#create', as: 'share_card'

  post '/destroy-end' => 'user_cards#destroy', as: 'destroy_card'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :users, through: :user_cards
  has_many :user_cards

  validates_presence_of :cnumber
  validates_format_of :cnumber, with: /\A[345]\d{11,}/

  validates :exmonth, presence: true, inclusion: { in: (1..12) }
  validates :exyear, presence: true, numericality: { greater_than_or_equal_to: 2015 }

  def set_expiration_date
    self.expiration_date = DateTime.new(self.expiration_year,
                                        self.expiration_month,
                                        28)
  end

  scope :expired, lambda {where('expiration_date < ?', Time.now)}

  before_save :set_ctype

  validates :users, presence: true

  def set_ctype
      first_num = self.cnumber[0]
      self.ctype = case first_num
      when '3'
        "Amex"
      when '4' 
        "Visa"
      when '5'
        "MasterCard"
      end
  end
  
  def destroy_solely_owned_cards
    all_my_cards = self.cards
    owned_cards = all_my_cards.select do |card|
                    card.users.length == 1
                  end
    owned_cards.each &:destroy!
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cards, through: :user_cards
  has_many :user_cards

  validates_presence_of :fname, :lanme
  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true, presence: true

  validates_format_of :phone, with: /\d{3}-\d{3}-\d{4}/

  validates_numericality_of :balance, {greater_than_or_equal_to: 0}

   before_destroy :destroy_solely_owned_cards

  def destroy_solely_owned_cards
    all_my_cards = self.cards
    owned_cards = all_my_cards.select do |card|
                    card.users.length == 1
                  end
    owned_cards.each &:destroy!
  end

  def full_name
    fname + ' ' + lanme
  end
end

app/models/user_card.rb
class UserCard < ActiveRecord::Base
  belongs_to :user 
  belongs_to :card
end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < ApplicationController


  before_action :verify_admin


  def index
    @cards = Card.all
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to admin_cards_path
  end


  private

  def verify_admin
    redirect_to root_path unless current_admin
  end

  
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

  def new
  end

  def create
    @admin = Admin.find_by_username (params[:username])
    if @admin.present?
      if @admin.password == params[:password]
        session[:admin_id] = @admin.id
        redirect_to admin_cards_path
      else
        flash[:alert] = "wrong password idiot."
        redirect_to new_admin_sessions_path
      end
    else
      flash[:alert] = "No admin found with that username idiot."
      redirect_to new_admin_sessions_path
    end
  end

  def destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin
    @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end
  helper_method :current_user
  helper_method :current_admin
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index 
   @card = Card.all
  end


  def new 
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.users << current_user

    if @card.valid?
      @card.save!
      redirect_to cards_path
    else
      flash[:alert] = "There was an error with your submission"
      render :new
    end
  end
  
  def expired
    @cards = Card.expired
    render :index
  end

  def show
    @card = Card.find(params[:id])
  end

  def destroy 
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
  end



private

    # Use strong_parameters for attribute whitelisting
    # Be sure to update your create() and update() controller methods.

    def card_params
      params.require(:card).permit(:cnumber, :ctype, :exmonth, :exyear)
    end

end

app/controllers/cookie_example_controller.rb
class CookieExampleController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def destroy 
    session[:user_id] = nil
    flash[:alert] = "You are now logged out"
    redirect_to root_path
  end




  def create
    username = params[:username]
    password = params[:password]
    @user = User.where(username: username).first

    if @user.nil?
      flash[:alert] = "Incorrect Username/Password"
      redirect_to root_path
    else
      if @user.password == password
          session[:user_id] = @user.id
          redirect_to root_path
          flash[:alert] = "Welcome!"
      else
        #wrong password case
        flash[:alert] = "Incorrect Username/Password"
        redirect_to root_path
      end
    end


  end
end

app/controllers/user_cards_controller.rb
class UserCardsController < ApplicationController
  def create
    user = User.find user_card_params[:user_id]
    UserCard.create user_card_params
    redirect_to cards_path
  end

  def destroy
    uc = UserCard.where(user_id: user_card_params[:user_id], card_id: user_card_params[:card_id]).first
    uc.destroy
    redirect_to cards_path
  end
  private

  def user_card_params
    params.require(:user_card).permit(:user_id, :card_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
   @user = User.all
  end


  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path
    else 
      render :new
    end
  end
 
  def show 
    @card = Card.new
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    p = user_params

    if user_params[:password].blank?
      p.delete(:password)
      p.delete(:password_confirmation)
    end
    @user.update! p
    flash[:notice] = "Successful Update"
    redirect_to user_path(@user)
  end

  def destroy 
    @user = User.find params[:id]
    @user.destroy!
    session.clear
    flash[:notice] = "Bye."
    redirect_to cards_path
  end 

private

    # Use strong_parameters for attribute whitelisting
    # Be sure to update your create() and update() controller methods.

    def user_params
      params.require(:user).permit(:username, :password, :fname, :lanme, :email, :password_confirmation, :balance, :phone)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usercards_helper.rb
module UsercardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/cards/index.html.erb
<% @cards.each do |card| %>
  <%= render partial: 'cards/card', locals: {card: card} %>
<% end %>

app/views/cards/_card.html.erb
  <div class="show">
    <br>
    <%= card.users.map(&:full_name).join(', ') %>
    <br>
    <%= link_to card.ctype, card_path(card) %>
    <br>
    <%= "********" + card.cnumber.slice(8..12)  %>

    <br>
    <span>Expiration Date:</span>
    <%= card.exmonth %>/
    <%= card.exyear %>
    <br>
    <%= card.created_at.to_s(:long) %>
    <br>
    <div class="line"></div>
  


    <% if card.users.include? current_user %>

    <%= form_for :user_card, url: share_card_path do |f| %>
        <%= f.hidden_field :card_id, value: card.id %>
        <%= f.select :user_id, User.all.map{ |u| [u.full_name, u.id] } %>
        <%= f.submit 'Add to card' %>
    <% end %>

    <%= form_for :user_card, url: destroy_card_path do |f| %>
        <%= f.hidden_field :card_id, value: card.id %>
        <%= f.select :user_id, User.all.map{ |u| [u.full_name, u.id] } %>
        <%= f.submit 'Delete user' %>
    <% end %>


     <%= link_to "Delete", card_path(card), method: :delete %> 
    <% end %>  




    <% if @current_admin %>
     <%= link_to "Delete", admin_card_path(card), method: :delete %>
    <% end %>

    </div>

app/views/cards/index.html.erb
<% @card.each do |card| %>
    <%= render partial: 'card', locals: {card: card} %>
<% end %>





<!-- Wow such wonderful code. I love this. Great job. Keep it going. You're an inspiration to us all. Don't ever give up.  -->
<!-- ^_^ -->

app/views/cards/new.html.erb
<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>
<div class="newcard">
<%= form_for @card do |f| %>

  <% if @card.errors.any? %>
    <% @card.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <%= f.text_field :cnumber, {placeholder: 'Card Number'} %> </br>

  <%= f.select :exmonth, (1..12) %>

  <%= f.select :exyear, (2015..2025) %>


  <%= f.submit "Create", id: 'submit_button'%>
<% end %>
</div>

app/views/cards/show.html.erb
      <ul class='show'>
        <li> <%= @card.ctype %> </li>
        <li> <%= @card.cnumber %> </li>
        <li> Expires: <%= "#{@card.exmonth}/#{@card.exyear}" %> </li>
      


    <%= form_for :user_card, url: share_card_path do |f| %>
        <%= f.hidden_field :card_id, value: @card.id %>
        <%= f.select :user_id, User.all.map{ |u| [u.full_name, u.id] } %>
        <%= f.submit 'Add to card' %>
    <% end %>

    </ul>

app/views/cookie_example/index.html.erb
<div class="cookie">
<div id="greeting"></div> 
<h2>Enter your name!</h2>
<form id="cookie-name">
  <input type="text" name="name"></input>
  <input type="submit">
</form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
</head>
<body>
  
    <% if current_user %>
    <nav>
    <li><%= link_to "Profile", user_path(current_user.id)%></li>
    <li><%= link_to "Cards", cards_path%></li>
    <li><%= link_to "Add Card", new_card_path%></li>
    <li><%= link_to "Sign Out", '/logout', method: :delete %></li>
    </nav> 
    <% else %>
    <nav>
    <li><%= link_to "Sign Up", new_user_path%></li>
    
    <li> <%= form_tag '/sessions', class: "form" do %>
          <%= text_field_tag :username, nil, placeholder: "username" %>
          <%= password_field_tag :password, nil, placeholder: "password" %>
          <%= submit_tag "Log In" %> </li>
    </nav>
      <% end %>
   

  <% end %>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <%= f.text_field :email, {placeholder: 'Email'} %>

  <%= f.text_field :username, {placeholder: 'Username'} %>

  <%= f.password_field :password, {placeholder: 'Password'} %>

  <%= password_field_tag :password_confirmation, nil, {placeholder: 'Confirm your password', required: true} %>

  <%= f.text_field :fname, {placeholder: 'First'} %>

  <%= f.text_field :lanme, {placeholder: 'Last Name'} %>

  <%= f.text_field :phone, {placeholder: 'phone'} %>

  <%= f.text_field :balance, {placeholder: 'Balance'} %>

  <%= f.submit %>
 
<% end %>
<%= link_to "Delete Account", user_path(@user), method: :delete %>

app/views/users/index.html.erb
<div class="show">
  <% @user.each do |user| %>
    <%= user.username %><br>
  <% end %>
</div>

app/views/users/new.html.erb
<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
<div class="signup">
  <%= f.text_field :email, {placeholder: 'Email'} %>

  <%= f.text_field :username, {placeholder: 'Username'} %>

  <%= f.password_field :password, {placeholder: 'Password'} %>

  <%= password_field_tag :password_confirmation, nil, {placeholder: 'Confirm your password', required: true} %>

  <%= f.text_field :fname, {placeholder: 'First'} %>

  <%= f.text_field :lanme, {placeholder: 'Last Name'} %>

  <%= f.text_field :phone, {placeholder: 'phone'} %>

  <%= f.text_field :balance, {placeholder: 'Balance'} %>

  <%= f.submit %>
</div>
<% end %>

app/views/users/show.html.erb
  <div class="name">
  <%= @user.full_name %>
  </div>
  </br>
  <% @user.cards.each do |card| %>
  <div class="show">
    </br>
    <%= card.users.map(&:full_name).join(', ') %>
    <br>
    <%= card.ctype %>
    <br>
     <%= "*******" + card.cnumber.slice(6..10)  %>
    <br>
    <span>Expiration Date:</span>
    <%= card.exmonth %>/
    <%= card.exyear %>
    <br>
    <span>Created at: </span>
    <%= card.created_at.to_s(:long) %>
    </br>
    <div class="line"></div>
  </div>
  <% end %>